### ISSUE TITLE
Histogrammer Haskell Implementation Volunteer

### ISSUE THREAD

**Issue by svanderbleek** [histogrammar/histogrammar-multilang#41]
Hey! I wasn't sure where to put this. I'd be interested in doing a Haskell implementation potentially. Perhaps we can talk more at StrangeLoop? I'm @haskellandchill on twitter and in StrangeLoop slack. Thanks!

**Comment by jpivarski** [comment]
That would be fantastic, and yes, this is the right place to ask. Let's talk more at StrangeLoop.

In fact, while writing my talk, I'm feeling uneasy about saying that Histogrammar has a "functional" API because even though the aggregators take a function as an argument, the `fill` method mutates state. Well, `fill` is the _only_ kind of method that mutates state, and in a controlled, well-specified, way. I was thinking of saying, "If there's ever a Haskell implementation of the API, a `filled` method could simply return a filled copy of the original aggregator. There's nothing intrinsic to in-place operations; it's just a performance consideration." And maybe you'll provide an example of that.

Looking forward to meeting you in person. I'll leave this issue open until we have a plan and the beginnings of a `histogrammar-haskell` repo.
